{
    "schema_version": "1.7.3",
    "id": "JLSEC-2025-89",
    "modified": "2025-10-17T17:40:51.659Z",
    "published": "2025-10-17T17:40:51.659Z",
    "upstream": [
        "CVE-2025-32414"
    ],
    "summary": "In libxml2 before 2.13.8 and 2.14.x before 2.14.2, out-of-bounds memory access can occur in the Pyth...",
    "details": "In libxml2 before 2.13.8 and 2.14.x before 2.14.2, out-of-bounds memory access can occur in the Python API (Python bindings) because of an incorrect return value. This occurs in xmlPythonFileRead and xmlPythonFileReadRaw because of a difference between bytes and characters.",
    "affected": [
        {
            "ranges": [
                {
                    "type": "SEMVER",
                    "events": [
                        {
                            "introduced": "0"
                        },
                        {
                            "fixed": "2.13.8+0"
                        },
                        {
                            "introduced": "2.14.1+0"
                        },
                        {
                            "fixed": "2.14.4+0"
                        }
                    ]
                }
            ],
            "package": {
                "ecosystem": "Julia",
                "name": "XML2_jll",
                "purl": "pkg:julia/XML2_jll?uuid=02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"
            }
        }
    ],
    "references": [
        {
            "type": "WEB",
            "url": "https://gitlab.gnome.org/GNOME/libxml2/-/issues/889"
        },
        {
            "type": "WEB",
            "url": "https://gitlab.gnome.org/GNOME/libxml2/-/issues/889"
        }
    ],
    "database_specific": {
        "license": "CC-BY-4.0",
        "sources": [
            {
                "id": "CVE-2025-32414",
                "imported": "2025-10-17T17:21:55.890Z",
                "modified": "2025-04-23T19:09:35.517Z",
                "published": "2025-04-08T03:15:15.940Z",
                "url": "https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2025-32414",
                "html_url": "https://nvd.nist.gov/vuln/detail/CVE-2025-32414"
            }
        ]
    }
}